[options]
admin_passwd = cenoq28004668
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

http_enable = True
http_interface = 0.0.0.0
http_port = 8069
gevent_port = 8072
proxy_mode = False

workers = 0
max_cron_threads = 1

log_level = info
log_handler = :INFO

list_db = True
