{
    "name": "GGAndy 包租代管",
    "summary": "物件、房東、房客、租約、收租與維修管理",
    "version": "19.0.1.0.0",
    "category": "Services/Real Estate",
    "author": "GGAndy",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "account",
    ],
    "data": [
        "security/property_management_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/product_data.xml",
        "views/property_views.xml",
        "views/property_unit_views.xml",
        "views/lease_views.xml",
        "views/rent_schedule_views.xml",
        "views/maintenance_request_views.xml",
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
